name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "pnpm"
      - name: "Install Dependencies"
        run: pnpm i
      - name: Build Project
        run: pnpm run bundle
      - name: Zip Project
        run: zip -r module.zip lib module.json LICENSE README.md
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "module.zip"
          generateReleaseNotes: true
          draft: true
